### ISSUE TITLE
Resources are missing from repo

### ISSUE THREAD

**Issue by jnccloud** [DemmyDemon/qb-fishy#1]
Hey bud, I've been tinkering with your weed script and was so blown away at how well engineered it was I was looking through your repos to see what else I could learn from.

I saw this repo and was going to try it out (I've never seen it before but reminds me of some fish table games I've seen IRL) but realized the fishing code isn't actually in the repo but the documentation has been updated a few times with more instructions. Figured it was an oversight? 

![image](https://github.com/DemmyDemon/qb-fishy/assets/58707473/51400c68-53cb-4384-bc59-ab321258c35c)

Regardless, looking forward to trying it out! 

And out of curiosity.. are you a computer science or mathematics major? I'm a systems engineer and the weed code is more advanced than production corporate code I've seen some 40 year veterans spit out.

**Comment by DemmyDemon** [comment]
qb-fishy is intentionally not released. The code exists, and runs well, but has not been published. This is not an oversight.

I'd like to hope most veterans can implement a quadtree, but a lot of corpo programmers get stuck doing the same thing for 40 years. They get absurdly good at it, and even if it's not as "sexy" as optimizing an octree, it's still very useful to society. ;-)

No, I did not major in maff.

**Comment by jnccloud** [comment]
> qb-fishy is intentionally not released. The code exists, and runs well, but has not been published. This is not an oversight.
> 
> I'd like to hope most veterans can implement a quadtree, but a lot of corpo programmers get stuck doing the same thing for 40 years. They get absurdly good at it, and even if it's not as "sexy" as optimizing an octree, it's still very useful to society. ;-)
> 
> No, I did not major in maff.

Regardless, it's some fun code to read. Thanks for clarifying. Do you have any plans to release it at some point?

**Comment by DemmyDemon** [comment]
No, not at this time.
